"""
Static ticker metadata — name, sector, country.
Used as primary source; yfinance .info is fallback only.
Covers ~180 tickers: S&P 500 majors, international large caps, ETFs.
"""

TICKER_META: dict[str, dict] = {
    # ── Technology ────────────────────────────────────────────────────────────
    "AAPL":  {"name": "Apple Inc.",                "sector": "Technology",             "country": "United States"},
    "MSFT":  {"name": "Microsoft Corp.",           "sector": "Technology",             "country": "United States"},
    "NVDA":  {"name": "NVIDIA Corp.",              "sector": "Technology",             "country": "United States"},
    "AMD":   {"name": "Advanced Micro Devices",    "sector": "Technology",             "country": "United States"},
    "INTC":  {"name": "Intel Corp.",               "sector": "Technology",             "country": "United States"},
    "QCOM":  {"name": "Qualcomm Inc.",             "sector": "Technology",             "country": "United States"},
    "AVGO":  {"name": "Broadcom Inc.",             "sector": "Technology",             "country": "United States"},
    "TXN":   {"name": "Texas Instruments",         "sector": "Technology",             "country": "United States"},
    "MU":    {"name": "Micron Technology",         "sector": "Technology",             "country": "United States"},
    "AMAT":  {"name": "Applied Materials",         "sector": "Technology",             "country": "United States"},
    "LRCX":  {"name": "Lam Research",              "sector": "Technology",             "country": "United States"},
    "KLAC":  {"name": "KLA Corp.",                 "sector": "Technology",             "country": "United States"},
    "ADBE":  {"name": "Adobe Inc.",                "sector": "Technology",             "country": "United States"},
    "CRM":   {"name": "Salesforce Inc.",           "sector": "Technology",             "country": "United States"},
    "ORCL":  {"name": "Oracle Corp.",              "sector": "Technology",             "country": "United States"},
    "NOW":   {"name": "ServiceNow Inc.",           "sector": "Technology",             "country": "United States"},
    "SNOW":  {"name": "Snowflake Inc.",            "sector": "Technology",             "country": "United States"},
    "PLTR":  {"name": "Palantir Technologies",     "sector": "Technology",             "country": "United States"},
    "UBER":  {"name": "Uber Technologies",         "sector": "Technology",             "country": "United States"},
    "DDOG":  {"name": "Datadog Inc.",              "sector": "Technology",             "country": "United States"},
    "CRWD":  {"name": "CrowdStrike Holdings",      "sector": "Technology",             "country": "United States"},
    "PANW":  {"name": "Palo Alto Networks",        "sector": "Technology",             "country": "United States"},
    "NET":   {"name": "Cloudflare Inc.",           "sector": "Technology",             "country": "United States"},
    "ZS":    {"name": "Zscaler Inc.",              "sector": "Technology",             "country": "United States"},
    "OKTA":  {"name": "Okta Inc.",                 "sector": "Technology",             "country": "United States"},
    "HUBS":  {"name": "HubSpot Inc.",              "sector": "Technology",             "country": "United States"},
    "SMCI":  {"name": "Super Micro Computer",      "sector": "Technology",             "country": "United States"},
    "SHOP":  {"name": "Shopify Inc.",              "sector": "Technology",             "country": "Canada"},
    "ARM":   {"name": "Arm Holdings",              "sector": "Technology",             "country": "United Kingdom"},
    "ASML":  {"name": "ASML Holding",              "sector": "Technology",             "country": "Netherlands"},
    "TSM":   {"name": "Taiwan Semiconductor",      "sector": "Technology",             "country": "Taiwan"},
    "SAP":   {"name": "SAP SE",                    "sector": "Technology",             "country": "Germany"},
    "MSTR":  {"name": "MicroStrategy",             "sector": "Technology",             "country": "United States"},
    "IBM":   {"name": "IBM Corp.",                 "sector": "Technology",             "country": "United States"},
    "HPQ":   {"name": "HP Inc.",                   "sector": "Technology",             "country": "United States"},
    "DELL":  {"name": "Dell Technologies",         "sector": "Technology",             "country": "United States"},

    # ── Communication Services ─────────────────────────────────────────────────
    "GOOGL": {"name": "Alphabet Inc. (A)",         "sector": "Communication Services", "country": "United States"},
    "GOOG":  {"name": "Alphabet Inc. (C)",         "sector": "Communication Services", "country": "United States"},
    "META":  {"name": "Meta Platforms",            "sector": "Communication Services", "country": "United States"},
    "NFLX":  {"name": "Netflix Inc.",              "sector": "Communication Services", "country": "United States"},
    "DIS":   {"name": "Walt Disney Co.",           "sector": "Communication Services", "country": "United States"},
    "CMCSA": {"name": "Comcast Corp.",             "sector": "Communication Services", "country": "United States"},
    "T":     {"name": "AT&T Inc.",                 "sector": "Communication Services", "country": "United States"},
    "VZ":    {"name": "Verizon Communications",    "sector": "Communication Services", "country": "United States"},
    "TMUS":  {"name": "T-Mobile US",               "sector": "Communication Services", "country": "United States"},
    "SPOT":  {"name": "Spotify Technology",        "sector": "Communication Services", "country": "Sweden"},
    "SNAP":  {"name": "Snap Inc.",                 "sector": "Communication Services", "country": "United States"},
    "PINS":  {"name": "Pinterest Inc.",            "sector": "Communication Services", "country": "United States"},
    "RBLX":  {"name": "Roblox Corp.",              "sector": "Communication Services", "country": "United States"},
    "WBD":   {"name": "Warner Bros. Discovery",    "sector": "Communication Services", "country": "United States"},

    # ── Consumer Cyclical ──────────────────────────────────────────────────────
    "AMZN":  {"name": "Amazon.com Inc.",           "sector": "Consumer Cyclical",      "country": "United States"},
    "TSLA":  {"name": "Tesla Inc.",                "sector": "Consumer Cyclical",      "country": "United States"},
    "HD":    {"name": "Home Depot",                "sector": "Consumer Cyclical",      "country": "United States"},
    "MCD":   {"name": "McDonald's Corp.",          "sector": "Consumer Cyclical",      "country": "United States"},
    "NKE":   {"name": "Nike Inc.",                 "sector": "Consumer Cyclical",      "country": "United States"},
    "LOW":   {"name": "Lowe's Companies",          "sector": "Consumer Cyclical",      "country": "United States"},
    "SBUX":  {"name": "Starbucks Corp.",           "sector": "Consumer Cyclical",      "country": "United States"},
    "TGT":   {"name": "Target Corp.",              "sector": "Consumer Cyclical",      "country": "United States"},
    "BKNG":  {"name": "Booking Holdings",         "sector": "Consumer Cyclical",      "country": "United States"},
    "ABNB":  {"name": "Airbnb Inc.",               "sector": "Consumer Cyclical",      "country": "United States"},
    "F":     {"name": "Ford Motor Co.",            "sector": "Consumer Cyclical",      "country": "United States"},
    "GM":    {"name": "General Motors",            "sector": "Consumer Cyclical",      "country": "United States"},
    "TM":    {"name": "Toyota Motor",              "sector": "Consumer Cyclical",      "country": "Japan"},
    "SONY":  {"name": "Sony Group",                "sector": "Consumer Cyclical",      "country": "Japan"},
    "LVMUY": {"name": "LVMH Moët Hennessy",        "sector": "Consumer Cyclical",      "country": "France"},
    "RACE":  {"name": "Ferrari N.V.",              "sector": "Consumer Cyclical",      "country": "Italy"},
    "ROST":  {"name": "Ross Stores",               "sector": "Consumer Cyclical",      "country": "United States"},
    "ORLY":  {"name": "O'Reilly Automotive",       "sector": "Consumer Cyclical",      "country": "United States"},

    # ── Consumer Defensive ─────────────────────────────────────────────────────
    "WMT":   {"name": "Walmart Inc.",              "sector": "Consumer Defensive",     "country": "United States"},
    "COST":  {"name": "Costco Wholesale",          "sector": "Consumer Defensive",     "country": "United States"},
    "PG":    {"name": "Procter & Gamble",          "sector": "Consumer Defensive",     "country": "United States"},
    "KO":    {"name": "Coca-Cola Co.",             "sector": "Consumer Defensive",     "country": "United States"},
    "PEP":   {"name": "PepsiCo Inc.",              "sector": "Consumer Defensive",     "country": "United States"},
    "PM":    {"name": "Philip Morris Int'l",       "sector": "Consumer Defensive",     "country": "United States"},
    "MO":    {"name": "Altria Group",              "sector": "Consumer Defensive",     "country": "United States"},
    "CL":    {"name": "Colgate-Palmolive",         "sector": "Consumer Defensive",     "country": "United States"},
    "MDLZ":  {"name": "Mondelez International",    "sector": "Consumer Defensive",     "country": "United States"},
    "EL":    {"name": "Estée Lauder",              "sector": "Consumer Defensive",     "country": "United States"},
    "KHC":   {"name": "Kraft Heinz",               "sector": "Consumer Defensive",     "country": "United States"},
    "GIS":   {"name": "General Mills",             "sector": "Consumer Defensive",     "country": "United States"},
    "NESN":  {"name": "Nestlé S.A.",               "sector": "Consumer Defensive",     "country": "Switzerland"},

    # ── Healthcare ─────────────────────────────────────────────────────────────
    "JNJ":   {"name": "Johnson & Johnson",         "sector": "Healthcare",             "country": "United States"},
    "UNH":   {"name": "UnitedHealth Group",        "sector": "Healthcare",             "country": "United States"},
    "LLY":   {"name": "Eli Lilly and Co.",         "sector": "Healthcare",             "country": "United States"},
    "PFE":   {"name": "Pfizer Inc.",               "sector": "Healthcare",             "country": "United States"},
    "MRK":   {"name": "Merck & Co.",               "sector": "Healthcare",             "country": "United States"},
    "ABT":   {"name": "Abbott Laboratories",       "sector": "Healthcare",             "country": "United States"},
    "TMO":   {"name": "Thermo Fisher Scientific",  "sector": "Healthcare",             "country": "United States"},
    "DHR":   {"name": "Danaher Corp.",             "sector": "Healthcare",             "country": "United States"},
    "BMY":   {"name": "Bristol-Myers Squibb",      "sector": "Healthcare",             "country": "United States"},
    "AMGN":  {"name": "Amgen Inc.",                "sector": "Healthcare",             "country": "United States"},
    "GILD":  {"name": "Gilead Sciences",           "sector": "Healthcare",             "country": "United States"},
    "ISRG":  {"name": "Intuitive Surgical",        "sector": "Healthcare",             "country": "United States"},
    "VRTX":  {"name": "Vertex Pharmaceuticals",    "sector": "Healthcare",             "country": "United States"},
    "REGN":  {"name": "Regeneron Pharmaceuticals", "sector": "Healthcare",             "country": "United States"},
    "MRNA":  {"name": "Moderna Inc.",              "sector": "Healthcare",             "country": "United States"},
    "CI":    {"name": "Cigna Group",               "sector": "Healthcare",             "country": "United States"},
    "CVS":   {"name": "CVS Health",                "sector": "Healthcare",             "country": "United States"},
    "HCA":   {"name": "HCA Healthcare",            "sector": "Healthcare",             "country": "United States"},
    "NVO":   {"name": "Novo Nordisk",              "sector": "Healthcare",             "country": "Denmark"},
    "RHHBY": {"name": "Roche Holding",             "sector": "Healthcare",             "country": "Switzerland"},
    "AZN":   {"name": "AstraZeneca",               "sector": "Healthcare",             "country": "United Kingdom"},
    "GSK":   {"name": "GSK plc",                   "sector": "Healthcare",             "country": "United Kingdom"},
    "SNY":   {"name": "Sanofi",                    "sector": "Healthcare",             "country": "France"},
    "NVS":   {"name": "Novartis AG",               "sector": "Healthcare",             "country": "Switzerland"},

    # ── Financial Services ─────────────────────────────────────────────────────
    "JPM":   {"name": "JPMorgan Chase",            "sector": "Financial Services",     "country": "United States"},
    "BAC":   {"name": "Bank of America",           "sector": "Financial Services",     "country": "United States"},
    "WFC":   {"name": "Wells Fargo",               "sector": "Financial Services",     "country": "United States"},
    "GS":    {"name": "Goldman Sachs",             "sector": "Financial Services",     "country": "United States"},
    "MS":    {"name": "Morgan Stanley",            "sector": "Financial Services",     "country": "United States"},
    "C":     {"name": "Citigroup Inc.",            "sector": "Financial Services",     "country": "United States"},
    "BRK-B": {"name": "Berkshire Hathaway B",      "sector": "Financial Services",     "country": "United States"},
    "V":     {"name": "Visa Inc.",                 "sector": "Financial Services",     "country": "United States"},
    "MA":    {"name": "Mastercard Inc.",           "sector": "Financial Services",     "country": "United States"},
    "AXP":   {"name": "American Express",          "sector": "Financial Services",     "country": "United States"},
    "PYPL":  {"name": "PayPal Holdings",           "sector": "Financial Services",     "country": "United States"},
    "BLK":   {"name": "BlackRock Inc.",            "sector": "Financial Services",     "country": "United States"},
    "SCHW":  {"name": "Charles Schwab",            "sector": "Financial Services",     "country": "United States"},
    "USB":   {"name": "U.S. Bancorp",              "sector": "Financial Services",     "country": "United States"},
    "PNC":   {"name": "PNC Financial Services",    "sector": "Financial Services",     "country": "United States"},
    "COIN":  {"name": "Coinbase Global",           "sector": "Financial Services",     "country": "United States"},
    "HSBC":  {"name": "HSBC Holdings",             "sector": "Financial Services",     "country": "United Kingdom"},
    "UBS":   {"name": "UBS Group",                 "sector": "Financial Services",     "country": "Switzerland"},
    "BNP":   {"name": "BNP Paribas",               "sector": "Financial Services",     "country": "France"},
    "DB":    {"name": "Deutsche Bank",             "sector": "Financial Services",     "country": "Germany"},
    "SAN":   {"name": "Banco Santander",           "sector": "Financial Services",     "country": "Spain"},

    # ── Energy ─────────────────────────────────────────────────────────────────
    "XOM":   {"name": "ExxonMobil Corp.",          "sector": "Energy",                 "country": "United States"},
    "CVX":   {"name": "Chevron Corp.",             "sector": "Energy",                 "country": "United States"},
    "COP":   {"name": "ConocoPhillips",            "sector": "Energy",                 "country": "United States"},
    "SLB":   {"name": "SLB (Schlumberger)",        "sector": "Energy",                 "country": "United States"},
    "EOG":   {"name": "EOG Resources",             "sector": "Energy",                 "country": "United States"},
    "MPC":   {"name": "Marathon Petroleum",        "sector": "Energy",                 "country": "United States"},
    "PSX":   {"name": "Phillips 66",               "sector": "Energy",                 "country": "United States"},
    "OXY":   {"name": "Occidental Petroleum",      "sector": "Energy",                 "country": "United States"},
    "BP":    {"name": "BP plc",                    "sector": "Energy",                 "country": "United Kingdom"},
    "SHEL":  {"name": "Shell plc",                 "sector": "Energy",                 "country": "United Kingdom"},
    "TTE":   {"name": "TotalEnergies",             "sector": "Energy",                 "country": "France"},
    "ENB":   {"name": "Enbridge Inc.",             "sector": "Energy",                 "country": "Canada"},

    # ── Industrials ────────────────────────────────────────────────────────────
    "BA":    {"name": "Boeing Co.",                "sector": "Industrials",            "country": "United States"},
    "CAT":   {"name": "Caterpillar Inc.",          "sector": "Industrials",            "country": "United States"},
    "GE":    {"name": "GE Aerospace",              "sector": "Industrials",            "country": "United States"},
    "HON":   {"name": "Honeywell Int'l",           "sector": "Industrials",            "country": "United States"},
    "RTX":   {"name": "RTX Corp.",                 "sector": "Industrials",            "country": "United States"},
    "LMT":   {"name": "Lockheed Martin",           "sector": "Industrials",            "country": "United States"},
    "MMM":   {"name": "3M Company",                "sector": "Industrials",            "country": "United States"},
    "DE":    {"name": "Deere & Company",           "sector": "Industrials",            "country": "United States"},
    "UPS":   {"name": "United Parcel Service",     "sector": "Industrials",            "country": "United States"},
    "FDX":   {"name": "FedEx Corp.",               "sector": "Industrials",            "country": "United States"},
    "NOC":   {"name": "Northrop Grumman",          "sector": "Industrials",            "country": "United States"},
    "GD":    {"name": "General Dynamics",          "sector": "Industrials",            "country": "United States"},
    "ITW":   {"name": "Illinois Tool Works",       "sector": "Industrials",            "country": "United States"},
    "ETN":   {"name": "Eaton Corp.",               "sector": "Industrials",            "country": "Ireland"},
    "EMR":   {"name": "Emerson Electric",          "sector": "Industrials",            "country": "United States"},
    "WM":    {"name": "Waste Management",          "sector": "Industrials",            "country": "United States"},
    "AIRBUS":{"name": "Airbus SE",                 "sector": "Industrials",            "country": "France"},

    # ── Basic Materials ────────────────────────────────────────────────────────
    "LIN":   {"name": "Linde plc",                 "sector": "Basic Materials",        "country": "Ireland"},
    "APD":   {"name": "Air Products",              "sector": "Basic Materials",        "country": "United States"},
    "FCX":   {"name": "Freeport-McMoRan",          "sector": "Basic Materials",        "country": "United States"},
    "NEM":   {"name": "Newmont Corp.",             "sector": "Basic Materials",        "country": "United States"},
    "ALB":   {"name": "Albemarle Corp.",           "sector": "Basic Materials",        "country": "United States"},
    "BHP":   {"name": "BHP Group",                 "sector": "Basic Materials",        "country": "Australia"},
    "RIO":   {"name": "Rio Tinto",                 "sector": "Basic Materials",        "country": "United Kingdom"},
    "VALE":  {"name": "Vale S.A.",                 "sector": "Basic Materials",        "country": "Brazil"},

    # ── Real Estate ────────────────────────────────────────────────────────────
    "AMT":   {"name": "American Tower",            "sector": "Real Estate",            "country": "United States"},
    "PLD":   {"name": "Prologis Inc.",             "sector": "Real Estate",            "country": "United States"},
    "EQIX":  {"name": "Equinix Inc.",              "sector": "Real Estate",            "country": "United States"},
    "CCI":   {"name": "Crown Castle",              "sector": "Real Estate",            "country": "United States"},
    "SPG":   {"name": "Simon Property Group",      "sector": "Real Estate",            "country": "United States"},
    "O":     {"name": "Realty Income",             "sector": "Real Estate",            "country": "United States"},
    "DLR":   {"name": "Digital Realty Trust",      "sector": "Real Estate",            "country": "United States"},

    # ── Utilities ──────────────────────────────────────────────────────────────
    "NEE":   {"name": "NextEra Energy",            "sector": "Utilities",              "country": "United States"},
    "DUK":   {"name": "Duke Energy",               "sector": "Utilities",              "country": "United States"},
    "SO":    {"name": "Southern Company",          "sector": "Utilities",              "country": "United States"},
    "D":     {"name": "Dominion Energy",           "sector": "Utilities",              "country": "United States"},
    "AEP":   {"name": "American Electric Power",   "sector": "Utilities",              "country": "United States"},
    "CEG":   {"name": "Constellation Energy",      "sector": "Utilities",              "country": "United States"},
    "VST":   {"name": "Vistra Corp.",              "sector": "Utilities",              "country": "United States"},
    "EXC":   {"name": "Exelon Corp.",              "sector": "Utilities",              "country": "United States"},

    # ── ETFs — US Equity ───────────────────────────────────────────────────────
    "SPY":   {"name": "SPDR S&P 500 ETF",              "sector": "ETF — Large Cap US",        "country": "United States"},
    "QQQ":   {"name": "Invesco QQQ (Nasdaq 100)",      "sector": "ETF — Tech/Growth US",      "country": "United States"},
    "IWM":   {"name": "iShares Russell 2000 ETF",      "sector": "ETF — Small Cap US",        "country": "United States"},
    "DIA":   {"name": "SPDR Dow Jones ETF",            "sector": "ETF — Large Cap US",        "country": "United States"},
    "VTI":   {"name": "Vanguard Total Market ETF",     "sector": "ETF — Large Cap US",        "country": "United States"},
    "VOO":   {"name": "Vanguard S&P 500 ETF",          "sector": "ETF — Large Cap US",        "country": "United States"},
    "IVV":   {"name": "iShares Core S&P 500",          "sector": "ETF — Large Cap US",        "country": "United States"},

    # ── ETFs — International Equity ────────────────────────────────────────────
    "VT":    {"name": "Vanguard Total World ETF",      "sector": "ETF — World",               "country": "United States"},
    "VEA":   {"name": "Vanguard Dev. Markets ex-US",   "sector": "ETF — Developed ex-US",     "country": "United States"},
    "EFA":   {"name": "iShares MSCI EAFE",             "sector": "ETF — Developed ex-US",     "country": "United States"},
    "EEM":   {"name": "iShares MSCI Emerging Markets", "sector": "ETF — Emerging Markets",    "country": "United States"},
    "VWO":   {"name": "Vanguard FTSE EM ETF",          "sector": "ETF — Emerging Markets",    "country": "United States"},
    "IEMG":  {"name": "iShares Core MSCI EM",          "sector": "ETF — Emerging Markets",    "country": "United States"},
    "FXI":   {"name": "iShares China Large-Cap",       "sector": "ETF — China",               "country": "United States"},
    "EWJ":   {"name": "iShares MSCI Japan",            "sector": "ETF — Japan",               "country": "United States"},
    "EWG":   {"name": "iShares MSCI Germany",          "sector": "ETF — Europe",              "country": "United States"},
    "EWU":   {"name": "iShares MSCI UK",               "sector": "ETF — Europe",              "country": "United States"},

    # ── ETFs — Sector (SPDR) ───────────────────────────────────────────────────
    "XLK":   {"name": "SPDR Technology ETF",           "sector": "Technology",                "country": "United States"},
    "XLV":   {"name": "SPDR Healthcare ETF",           "sector": "Healthcare",                "country": "United States"},
    "XLF":   {"name": "SPDR Financials ETF",           "sector": "Financial Services",        "country": "United States"},
    "XLE":   {"name": "SPDR Energy ETF",               "sector": "Energy",                    "country": "United States"},
    "XLY":   {"name": "SPDR Consumer Discret. ETF",    "sector": "Consumer Cyclical",         "country": "United States"},
    "XLP":   {"name": "SPDR Consumer Staples ETF",     "sector": "Consumer Defensive",        "country": "United States"},
    "XLI":   {"name": "SPDR Industrials ETF",          "sector": "Industrials",               "country": "United States"},
    "XLB":   {"name": "SPDR Materials ETF",            "sector": "Basic Materials",           "country": "United States"},
    "XLU":   {"name": "SPDR Utilities ETF",            "sector": "Utilities",                 "country": "United States"},
    "XLRE":  {"name": "SPDR Real Estate ETF",          "sector": "Real Estate",               "country": "United States"},
    "XLC":   {"name": "SPDR Comm. Services ETF",       "sector": "Communication Services",    "country": "United States"},

    # ── ETFs — Fixed Income ────────────────────────────────────────────────────
    "AGG":   {"name": "iShares Core US Aggregate Bond","sector": "ETF — Bonds (Agg)",         "country": "United States"},
    "BND":   {"name": "Vanguard Total Bond Market",    "sector": "ETF — Bonds (Agg)",         "country": "United States"},
    "TLT":   {"name": "iShares 20+ Year Treasury",     "sector": "ETF — Bonds (Long-term)",   "country": "United States"},
    "IEF":   {"name": "iShares 7-10 Year Treasury",    "sector": "ETF — Bonds (Mid-term)",    "country": "United States"},
    "SHY":   {"name": "iShares 1-3 Year Treasury",     "sector": "ETF — Bonds (Short-term)",  "country": "United States"},
    "LQD":   {"name": "iShares iBoxx Corp Bond",       "sector": "ETF — Bonds (Corp IG)",     "country": "United States"},
    "HYG":   {"name": "iShares High Yield Corp Bond",  "sector": "ETF — Bonds (High Yield)",  "country": "United States"},
    "JNK":   {"name": "SPDR Bloomberg High Yield",     "sector": "ETF — Bonds (High Yield)",  "country": "United States"},
    "TIP":   {"name": "iShares TIPS Bond",             "sector": "ETF — Bonds (TIPS)",        "country": "United States"},
    "EMB":   {"name": "iShares EM Bond USD",           "sector": "ETF — Bonds (EM)",          "country": "United States"},
    "MBB":   {"name": "iShares MBS Bond",              "sector": "ETF — Bonds (MBS)",         "country": "United States"},

    # ── ETFs — Alternatives & Commodities ─────────────────────────────────────
    "GLD":   {"name": "SPDR Gold Shares",              "sector": "ETF — Gold",                "country": "United States"},
    "IAU":   {"name": "iShares Gold Trust",            "sector": "ETF — Gold",                "country": "United States"},
    "SLV":   {"name": "iShares Silver Trust",          "sector": "ETF — Silver",              "country": "United States"},
    "GDX":   {"name": "VanEck Gold Miners ETF",        "sector": "ETF — Gold Miners",         "country": "United States"},
    "GDXJ":  {"name": "VanEck Junior Gold Miners",     "sector": "ETF — Gold Miners",         "country": "United States"},
    "USO":   {"name": "United States Oil Fund",        "sector": "ETF — Oil",                 "country": "United States"},
    "UNG":   {"name": "United States Natural Gas",     "sector": "ETF — Natural Gas",         "country": "United States"},
    "VNQ":   {"name": "Vanguard Real Estate ETF",      "sector": "Real Estate",               "country": "United States"},
    "IBIT":  {"name": "iShares Bitcoin Trust",         "sector": "ETF — Crypto",              "country": "United States"},
    "FBTC":  {"name": "Fidelity Wise Origin Bitcoin",  "sector": "ETF — Crypto",              "country": "United States"},

    # ── Volatility ─────────────────────────────────────────────────────────────
    "UVXY":  {"name": "ProShares Ultra VIX ST Futures","sector": "ETF — Volatility",          "country": "United States"},
    "SVXY":  {"name": "ProShares Short VIX",           "sector": "ETF — Volatility",          "country": "United States"},
}
